### ISSUE TITLE
Bug: Unable to get local plugins.json

### ISSUE THREAD

**Issue by tedraykov** [reactioncommerce/cli#113]
After the monorepo migration, the location of the `plugins.json` is changed and all its references need to be updated.

**Comment by brent-hoover** [comment]
Can you let me know what problems exactly this is CAUSING? I had no problem spinning up a project using the CLI

**Comment by tedraykov** [comment]
The `clone-api-plugins` was trying to get the remote `plugins.json` from the old location. I extracted the `getFileFromCore` function and I used it in the `create-api-plugins` action

**Comment by zenweasel** [comment]
Are you sure you tested with the latest version because that's already been fixed?
