### ISSUE TITLE
Demo command fails due to missing STORE_URL env variable

### ISSUE THREAD

**Issue by m5ingh** [reactioncommerce/cli#116]
## Issue Description
Reaction Demo command fails to start the api container due to Missing environment variables: STORE_URL

## Steps to Reproduce
1. reaction create-project demo demo-name
2. docker ps -a. api container exiting. 
3. logs show  Missing environment variables:
    STORE_URL: undefined Exiting with error code 1

## Possible Solution
add missing env variable  STORE_URL=http://localhost:4000 to cli/templates/demo/.api.env file.
added pull request

**Comment by brent-hoover** [comment]
Thanks for the bug report. Will try to get a fix out today

**Comment by m5ingh** [comment]
i have submitted a pr too

**Comment by m5ingh** [comment]
https://github.com/reactioncommerce/cli/pull/117
