### ISSUE TITLE
Add Commitlint to packages to enforce commit style for semantic release

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/cli#120]

**Comment by sushmitha-malae** [comment]
@zenweasel I would like to work on this issue, could you please assign this to me. Thanks!

**Comment by brent-hoover** [comment]
@sushmitha-malae done

**Comment by Vikki123** [comment]
Is this still being worked on ? If not i can pick this. @sushmitha-malae could you please confirm.

**Comment by sushmitha-malae** [comment]
@Vikki123 You can take this issue, i am working on something else.

**Comment by delagroove** [comment]
assigned to @Vikki123

**Comment by Vikki123** [comment]
@delagroove I have raised a PR https://github.com/reactioncommerce/cli/pull/128. Could you please review. Thanks !

**Comment by brent-hoover** [comment]
Sorry, @Vikki123 didn't see you assigned and someone had already beat you to this [here](https://github.com/reactioncommerce/cli/pull/125). Hopefully you still get credit for it
