### ISSUE TITLE
Update command is incorrect

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/cli#62]
Getting this message:

```
   ╭──────────────────────────────────────────────────╮
   │                                                  │
   │   Update available 0.0.0-development → 0.29.0    │
   │         Run npm i reaction-cli to update         │
   │                                                  │
   ╰──────────────────────────────────────────────────╯

```

 but it needs to be `npm i -g reaction-cli`

**Comment by akhilchoudhary2k** [comment]
Hii @zenweasel, I would like to work on this issue

**Comment by akhilchoudhary2k** [comment]
@zenweasel is there any slack channel we can start the discussion on ? 
Please assign me this issue.

**Comment by akhilchoudhary2k** [comment]
@zenweasel Please review the PR: https://github.com/reactioncommerce/cli/pull/127

**Comment by brent-hoover** [comment]
Thanks @akhilchoudhary2k! This change has been published

**Comment by akhilchoudhary2k** [comment]
Thanks, happy to help :)
