### ISSUE TITLE
When creating an api project, copy over integrations tests and add test script to package.json

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/cli#92]
Steps for making this work:

1. Copy over entire`test` directory from reaction core
2. Move `checkNodeVersion.csj` from "utils" to "src"
3. Add tests scripts to package.json
4. Copy over jest config
5. Copy over babel config

Needs to have Mongo running. The Jest setup needs to set the MONGO_URL to MONGO_URL=mongodb://localhost:27017/test

**Comment by zenweasel** [comment]
Steps for making this work:

1. Copy over entire`test` directory
2. Move checkNodeVersion.csj from "utils" to "src"
3. Add tests scripts
4. Copy over jest config
5. Copy over babel config

**Comment by aditya-padhi-kbl** [comment]
Hi @zenweasel ,

I was looking into this issue. 
While point 1 & 2 are done, I see that point 3 is already there here:- https://github.com/reactioncommerce/cli/blob/trunk/commands/create-project-api.js#L45

I am not sure when you mentioned copy over 4 & 5.  I couldn't find the respective config files in the repo.

Awaiting you reply please regarding the next set of actions.

Kind Regards,
Aditya

**Comment by aditya-padhi-kbl** [comment]
Please assign it to me, as I am taking a look into it

**Comment by brent-hoover** [comment]
@aditya-padhi-kbl These files now reside [here](https://github.com/reactioncommerce/reaction/tree/trunk/apps/reaction)

**Comment by aditya-padhi-kbl** [comment]
@zenweasel I have created a pull request https://github.com/reactioncommerce/cli/pull/133
Please review.

@zenweasel By mistake I closed the preview pull request as it was having some issues with sign-off commit message.  Sorry for the inconvenience :) 

Please consider https://github.com/reactioncommerce/cli/pull/133 as the final PR
